# Generated by Django 3.2.19 on 2023-05-09 09:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_userrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='images'),
        ),
    ]
