# Generated by Django 3.2.19 on 2023-05-09 13:11

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_userrecipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Save on book'), (1, 'Published')], default=0),
        ),
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
