# Generated by Django 3.2.19 on 2023-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230509_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cost',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(null=True),
        ),
    ]
