# Generated by Django 3.2.19 on 2023-05-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230511_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
