# Generated by Django 3.2.19 on 2023-05-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='excerpt',
        ),
    ]
